name: Sync Public to Private
on:
  push:
    branches:
      - staging

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout quests_private
        uses: actions/checkout@v4
        with:
          repository: The-Heroes-Journey-EQEMU/quests_private
          ref: staging
          token: ${{ secrets.REPOSITORY_KEY }}
          fetch-depth: 0  # Ensures full history is fetched

      - name: Add quests_public remote
        run: git remote add public https://github.com/The-Heroes-Journey-EQEMU/quests_public.git || true

      - name: Fetch full history to ensure common ancestor
        run: |
          git fetch --unshallow || true  # If repo is already unshallowed, this prevents failure
          git fetch public staging --no-tags

      - name: Enable Sparse Checkout (Exclude Workflows)
        run: |
          git sparse-checkout init --cone
          git sparse-checkout set ':!github/workflows'  # Exclude workflows

      - name: Fast-forward merge Public → Private (Excluding Workflows)
        run: |
          git merge --ff public/staging || (echo "Merge conflict! Manual intervention required." && exit 1)
          git push origin staging
