name: Sync Public to Private
on:
  push:
    branches:
      - staging

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout quests_private
        uses: actions/checkout@v4
        with:
          repository: The-Heroes-Journey-EQEMU/quests_private
          ref: staging
          token: ${{ secrets.REPOSITORY_KEY }}
          fetch-depth: 0

      - name: Add quests_public remote
        run: git remote add public https://github.com/The-Heroes-Journey-EQEMU/quests_public.git || true

      - name: Fetch full history
        run: |
          git fetch --unshallow || true
          git fetch public staging --no-tags

      - name: Set Git Identity
        run: |
          git config user.email "github-actions@heroesjourneyemu.com"
          git config user.name "GitHub Actions"

      - name: Fast-forward merge Public → Private (Preserve Workflows)
        run: |
          git merge --ff public/staging || (
            echo "Merge conflict detected! Resolving automatically..."

            # 1️⃣ Ignore .github/workflows (DO NOT MODIFY OR DELETE)
            git checkout --ours .github/workflows || true
            git checkout --theirs .github/workflows || true
            git reset HEAD .github/workflows || true

            # 2️⃣ Add new files from public if they don’t exist in private
            git diff --name-only --diff-filter=A public/staging | xargs -I {} git checkout public/staging -- {} || true

            # 3️⃣ Keep private versions of conflicting files (EXCEPT workflows)
            git diff --name-only --diff-filter=U | grep -v '^.github/workflows' | xargs git checkout --ours || true

            # 4️⃣ Finalize and commit resolution
            git add .
            git commit -m "Automatically resolved conflicts (kept private version, added new files from public, preserved workflows)"
          )

          git push origin staging
