name: Sync Public to Private
on:
  push:
    branches:
      - staging

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout quests_private
        uses: actions/checkout@v4
        with:
          repository: The-Heroes-Journey-EQEMU/quests_private
          ref: staging
          token: ${{ secrets.REPOSITORY_KEY }}
          fetch-depth: 0

      - name: Add quests_public remote
        run: git remote add public https://github.com/The-Heroes-Journey-EQEMU/quests_public.git || true

      - name: Fetch full history
        run: |
          git fetch --unshallow || true
          git fetch public staging --no-tags

      - name: Set Git Identity
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"

      - name: Enable Sparse Checkout
        run: |
          git sparse-checkout init --cone
          git sparse-checkout set ':!github/workflows'

      - name: Fast-forward merge Public → Private (Always Keep Private Version)
        run: |
          git merge --ff public/staging || (
            git checkout --ours . || true
            git add . || true
            git commit -m "Automatically resolved conflicts (kept private version)"
          )
          git push origin staging
